version: '{branch}-{build}'

install:
  - appveyor DownloadFile https://slproweb.com/download/Win32OpenSSL-1_0_2e.exe
  - Win32OpenSSL-1_0_2e.exe /sp- /silent /verysilent /suppressmsgboxes '/DIR=C:\OpenSSL-Win32'
  - appveyor DownloadFile http://download.qt.io/archive/qt/5.5/5.5.1/single/qt-everywhere-opensource-src-5.5.1.7z

build_script:
  - build.cmd

artifacts:
  - path: build\qtbase\lib\Qt5Network.dll
