language: cpp

os: osx

compiler: clang

before_install:
  - xcodebuild -showsdks

install:
  - >
    curl -sL https://github.com/AaronWallace/MacOSX_SDKs/tarball/ba4d5b3 | tar xz
    --directory /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs
    --strip-components=1 AaronWallace-MacOSX_SDKs-ba4d5b3/MacOSX10.8.sdk

before_script:
  - xcodebuild -showsdks

script:
  - ./build.sh

test: off
